on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.6
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.2'
    - run: raco pkg install --auto box-extra-lib/ box-extra/
    - run: raco test box-extra/
